# Generated by Django 4.1.7 on 2023-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_cnic_review_cnic1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cnic1',
        ),
        migrations.AddField(
            model_name='review',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
    ]
