# Generated by Django 4.1.7 on 2023-09-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_review_cnic1_review_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_age',
        ),
    ]
