# Generated by Django 4.1.7 on 2023-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
