# Generated by Django 4.1.7 on 2023-09-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
