# Generated by Django 4.1.7 on 2023-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_product_reviews_product_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews_count',
        ),
    ]
