# Generated by Django 4.1.7 on 2023-09-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cnic',
        ),
    ]
